// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidToken-0]
	_ = x[EOF-1]
	_ = x[Number-2]
	_ = x[Identifier-3]
	_ = x[Let-4]
	_ = x[Plus-5]
	_ = x[Minus-6]
	_ = x[Star-7]
	_ = x[Slash-8]
	_ = x[Equal-9]
	_ = x[LeftParen-10]
	_ = x[RightParen-11]
}

const _TokenType_name = "InvalidTokenEOFNumberIdentifierLetPlusMinusStarSlashEqualLeftParenRightParen"

var _TokenType_index = [...]uint8{0, 12, 15, 21, 31, 34, 38, 43, 47, 52, 57, 66, 76}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
