// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidToken-0]
	_ = x[EOF-1]
	_ = x[Number-2]
	_ = x[Identifier-3]
	_ = x[Let-4]
	_ = x[True-5]
	_ = x[False-6]
	_ = x[Plus-7]
	_ = x[Minus-8]
	_ = x[Star-9]
	_ = x[Slash-10]
	_ = x[Equal-11]
	_ = x[SemiColon-12]
	_ = x[LeftParen-13]
	_ = x[RightParen-14]
}

const _TokenType_name = "InvalidTokenEOFNumberIdentifierLetTrueFalsePlusMinusStarSlashEqualSemiColonLeftParenRightParen"

var _TokenType_index = [...]uint8{0, 12, 15, 21, 31, 34, 38, 43, 47, 52, 56, 61, 66, 75, 84, 94}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
