// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidToken-0]
	_ = x[EOF-1]
	_ = x[Number-2]
	_ = x[Identifier-3]
	_ = x[Let-4]
	_ = x[True-5]
	_ = x[False-6]
	_ = x[If-7]
	_ = x[Else-8]
	_ = x[Fn-9]
	_ = x[Int-10]
	_ = x[Bool-11]
	_ = x[Plus-12]
	_ = x[Minus-13]
	_ = x[Star-14]
	_ = x[Slash-15]
	_ = x[Equal-16]
	_ = x[Less-17]
	_ = x[LessEqual-18]
	_ = x[Greater-19]
	_ = x[GreaterEqual-20]
	_ = x[EqualEqual-21]
	_ = x[NotEqual-22]
	_ = x[And-23]
	_ = x[Or-24]
	_ = x[Not-25]
	_ = x[SemiColon-26]
	_ = x[LeftParen-27]
	_ = x[RightParen-28]
	_ = x[LeftCurlyBrace-29]
	_ = x[RightCurlyBrace-30]
	_ = x[Comma-31]
}

const _TokenType_name = "InvalidTokenEOFNumberIdentifierLetTrueFalseIfElseFnIntBoolPlusMinusStarSlashEqualLessLessEqualGreaterGreaterEqualEqualEqualNotEqualAndOrNotSemiColonLeftParenRightParenLeftCurlyBraceRightCurlyBraceComma"

var _TokenType_index = [...]uint8{0, 12, 15, 21, 31, 34, 38, 43, 45, 49, 51, 54, 58, 62, 67, 71, 76, 81, 85, 94, 101, 113, 123, 131, 134, 136, 139, 148, 157, 167, 181, 196, 201}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
