// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidToken-0]
	_ = x[EOF-1]
	_ = x[Number-2]
	_ = x[Identifier-3]
	_ = x[Let-4]
	_ = x[True-5]
	_ = x[False-6]
	_ = x[If-7]
	_ = x[Else-8]
	_ = x[Fn-9]
	_ = x[Int-10]
	_ = x[Bool-11]
	_ = x[Return-12]
	_ = x[Plus-13]
	_ = x[Minus-14]
	_ = x[Star-15]
	_ = x[Slash-16]
	_ = x[Equal-17]
	_ = x[Less-18]
	_ = x[LessEqual-19]
	_ = x[Greater-20]
	_ = x[GreaterEqual-21]
	_ = x[EqualEqual-22]
	_ = x[NotEqual-23]
	_ = x[And-24]
	_ = x[Or-25]
	_ = x[Not-26]
	_ = x[SemiColon-27]
	_ = x[LeftParen-28]
	_ = x[RightParen-29]
	_ = x[LeftCurlyBrace-30]
	_ = x[RightCurlyBrace-31]
	_ = x[Comma-32]
}

const _TokenType_name = "InvalidTokenEOFNumberIdentifierLetTrueFalseIfElseFnIntBoolReturnPlusMinusStarSlashEqualLessLessEqualGreaterGreaterEqualEqualEqualNotEqualAndOrNotSemiColonLeftParenRightParenLeftCurlyBraceRightCurlyBraceComma"

var _TokenType_index = [...]uint8{0, 12, 15, 21, 31, 34, 38, 43, 45, 49, 51, 54, 58, 64, 68, 73, 77, 82, 87, 91, 100, 107, 119, 129, 137, 140, 142, 145, 154, 163, 173, 187, 202, 207}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
