// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidToken-0]
	_ = x[EOF-1]
	_ = x[Number-2]
	_ = x[Identifier-3]
	_ = x[Let-4]
	_ = x[True-5]
	_ = x[False-6]
	_ = x[If-7]
	_ = x[Else-8]
	_ = x[Plus-9]
	_ = x[Minus-10]
	_ = x[Star-11]
	_ = x[Slash-12]
	_ = x[Equal-13]
	_ = x[Less-14]
	_ = x[LessEqual-15]
	_ = x[Greater-16]
	_ = x[GreaterEqual-17]
	_ = x[EqualEqual-18]
	_ = x[NotEqual-19]
	_ = x[Not-20]
	_ = x[SemiColon-21]
	_ = x[LeftParen-22]
	_ = x[RightParen-23]
	_ = x[LeftCurlyBrace-24]
	_ = x[RightCurlyBrace-25]
}

const _TokenType_name = "InvalidTokenEOFNumberIdentifierLetTrueFalseIfElsePlusMinusStarSlashEqualLessLessEqualGreaterGreaterEqualEqualEqualNotEqualNotSemiColonLeftParenRightParenLeftCurlyBraceRightCurlyBrace"

var _TokenType_index = [...]uint8{0, 12, 15, 21, 31, 34, 38, 43, 45, 49, 53, 58, 62, 67, 72, 76, 85, 92, 104, 114, 122, 125, 134, 143, 153, 167, 182}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
