// Code generated by "stringer -type=BaseType"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IntType-0]
	_ = x[BoolType-1]
}

const _BaseType_name = "IntTypeBoolType"

var _BaseType_index = [...]uint8{0, 7, 15}

func (i BaseType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BaseType_index)-1 {
		return "BaseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaseType_name[_BaseType_index[idx]:_BaseType_index[idx+1]]
}
